### PR TITLE
fix(runes): validations and cenotaph tracking

### LINKED ISSUE #541: Invalid rune etching returned from Runes API Get activity for a transaction endpoint
These two transactions contain runestones with etchings for the same rune name (rune names must be unique). So the latter runestone is invalid, however the Runes API activity for transaction endpoint is returning etching and receive activity for the invalid runestone.

```
9932c96a725000510688bdb05c4bcae70bb7bc0aa029dc8c0bd253827f95a9f6
0ef0f35e3507f85d9d3b771ee2b2cb790326ed4a996ae2a585055219d2e1e628
```

### LINKED ISSUE #571: Runes Fixes Progress Tracker
- [x] no commit validation
- [x] dynamic name validation
- [x] runestones containing etchings and flaw:overflow should not count as etchings
- [x] unit tests and utility tool for debugging these processes
- [x] fix cenotaph tracking column
- [x] add same validations for cenotaphs

### PR DESCRIPTION
**Pull request by ASuciuX**
Invalidate runes that do not have the etching_commit at least 5 blocks before the etching_reveal.

### CODE REVIEW

File: components/bitcoind/src/utils/bitcoind.rs [hunk 1]
```diff
@@ -43,6 +47,57 @@ pub fn bitcoind_get_chain_tip(config: &BitcoindConfig, ctx: &Context) -> BlockId
     }
 }
 
+/// Retrieves the block_height for a given blockhash.
+pub fn bitcoind_get_block_height(
+    bitcoin_rpc: &Client,
+    ctx: &Context,
+    blockhash: &BlockHash,
+) -> u32 {
+    loop {
```
Comment (rafaelcr) [inline components/bitcoind/src/utils/bitcoind.rs]: I don't think these functions should attempt to retry the RPC calls, we should propagate the error instead so we can adequately handle it and retry the entire block indexing or whatever we need to do, i.e. your return types should be `Result<u32, String>`

File: components/runes/src/db/cache/index_cache.rs [hunk 2]
```diff
@@ -1,8 +1,13 @@
 use std::{collections::HashMap, num::NonZeroUsize, str::FromStr};
 
 use bitcoin::{Network, ScriptBuf};
-use bitcoind::{try_debug, try_warn, types::bitcoin::TxIn, utils::Context};
-use config::Config;
+use bitcoind::{
+    bitcoincore_rpc::Client as BitcoinRPCClient,
```
Comment (rafaelcr) [inline components/runes/src/db/cache/index_cache.rs]: Nit, case should be `BitcoinRpcClient`

File: components/runes/src/db/cache/index_cache.rs [hunk 3]
```diff
@@ -160,8 +175,50 @@ impl IndexCache {
...
+            &rune,
+            self.tx_cache.location.block_height as u32,
+            inputs_counter,
+        )
+        .await
+        .unwrap_or(false);
+
+        if !is_valid_commitment {
+            try_debug!(ctx, "Invalid rune commitment for etching {}", rune);
+            return; // Skip invalid etchings
```
Comment (rafaelcr) [inline components/runes/src/db/cache/index_cache.rs]: Wouldn't you need to undo the `self.tx_cache.apply_etching` here if this is the case?

File: components/runes/src/db/cache/rune_validation.rs [hunk 4]
```diff
@@ -0,0 +1,686 @@
...
+    }
+
+    Ok(false)
+}
+
+/// Validates that a rune etching transaction has a proper commitment transaction with automatic reconnection.
+///
+/// This function wraps the core validation logic with connection error handling. If a connection
+/// error is detected, it will attempt to reconnect the Bitcoin RPC client and retry the validation.
+pub async fn rune_etching_has_valid_commit_with_reconnect(
```
Comment (rafaelcr) [inline components/runes/src/db/cache/rune_validation.rs]: Same here, I don't think we need reconnect logic at this level. Is there a special reason why you're doing it here? Maybe I'm missing something

**Review by rafaelcr — CHANGES_REQUESTED** [review]

**Review by rafaelcr — APPROVED** [review]
Great work @ASuciuX !
